upstreams:
  - id: whoelse
    path: /another-app/
    uri: http://another-app
  - id: prometheus
    path: /prometheus/
    uri: http://prometheus:9090
  - id: whoami
    path: /app/
    uri: http://app
